# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Trajectory-wise A-update for directed Gaussian RW-smoothed ALS
#'
#' Solves the block-tridiagonal system for the entire A trajectory
#' conditional on the B trajectory.
#'
#' @param Phi cube [n_row x n_col x Tt] of centered states
#' @param B_arr cube [n_col x n_col x Tt] of B operators (slices 1..Tt-1 used)
#' @param Omega cube [n_row x n_col x Tt] of 0/1 response masks
#' @param lambda RW penalty
#' @param mu level penalty
#' @return cube [n_row x n_row x Tt] of updated A operators
#' @keywords internal
#' @noRd
solve_A_trajectory_cpp <- function(Phi, B_arr, Omega, lambda, mu) {
    .Call(`_dbn_solve_A_trajectory_cpp`, Phi, B_arr, Omega, lambda, mu)
}

#' Trajectory-wise B-update for directed Gaussian RW-smoothed ALS
#'
#' Analogous to solve_A_trajectory_cpp, with N_t = X_t^T A_t^T as the
#' design matrix. Note the corrected matrix order per reviewer 2.
#'
#' @param Phi cube [n_row x n_col x Tt] of centered states
#' @param A_arr cube [n_row x n_row x Tt] of A operators (slices 1..Tt-1 used)
#' @param Omega cube [n_row x n_col x Tt] of 0/1 response masks
#' @param lambda RW penalty
#' @param mu level penalty
#' @return cube [n_col x n_col x Tt] of updated B operators
#' @keywords internal
#' @noRd
solve_B_trajectory_cpp <- function(Phi, A_arr, Omega, lambda, mu) {
    .Call(`_dbn_solve_B_trajectory_cpp`, Phi, A_arr, Omega, lambda, mu)
}

#' Compute the RW-smoothed ALS objective value
#'
#' @param Phi cube [n_row x n_col x Tt]
#' @param A_arr cube [n_row x n_row x Tt]
#' @param B_arr cube [n_col x n_col x Tt]
#' @param Omega cube [n_row x n_col x Tt]
#' @param lambda_A RW penalty on A
#' @param lambda_B RW penalty on B
#' @param mu_A level penalty on A
#' @param mu_B level penalty on B
#' @return scalar objective value
#' @keywords internal
#' @noRd
compute_tv_als_objective_cpp <- function(Phi, A_arr, B_arr, Omega, lambda_A, lambda_B, mu_A, mu_B) {
    .Call(`_dbn_compute_tv_als_objective_cpp`, Phi, A_arr, B_arr, Omega, lambda_A, lambda_B, mu_A, mu_B)
}

#' Stabilize spectral radius of a matrix
#' 
#' @param M Matrix to stabilize
#' @param threshold Maximum allowed spectral radius
#' @return Stabilized matrix
#' @keywords internal
#' @noRd
stabilize_spectral_radius <- function(M, threshold) {
    .Call(`_dbn_stabilize_spectral_radius`, M, threshold)
}

#' Safe Cholesky decomposition with regularization
#' 
#' @param L Output lower triangular matrix
#' @param A Input matrix
#' @param reg Regularization parameter
#' @return Success indicator
#' @keywords internal
#' @noRd
safe_cholesky <- function(L, A, reg) {
    .Call(`_dbn_safe_cholesky`, L, A, reg)
}

#' Ensure a matrix is positive definite
#' 
#' @param M Input matrix
#' @param min_eigenvalue Minimum eigenvalue threshold
#' @return Positive definite matrix
#' @keywords internal
#' @noRd
ensure_positive_definite <- function(M, min_eigenvalue) {
    .Call(`_dbn_ensure_positive_definite`, M, min_eigenvalue)
}

#' Check if VAR process is stationary
#' 
#' @param A Autoregressive coefficient matrix
#' @param B Bilinear coefficient matrix  
#' @param p Number of actors
#' @param q Latent dimension
#' @return Stationarity indicator
#' @keywords internal
#' @noRd
is_stationary <- function(A, B, p, q) {
    .Call(`_dbn_is_stationary`, A, B, p, q)
}

#' @keywords internal
#' @noRd
batch_update_Z_ordinal <- function(R_4d, Z_4d, Theta_4d, M, IR, n_row, n_col, p, Tt) {
    .Call(`_dbn_batch_update_Z_ordinal`, R_4d, Z_4d, Theta_4d, M, IR, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
batch_update_Z_ordinal_fast <- function(R_4d, Z_4d, Theta_4d, M, IR, IR_time_indices, n_row, n_col, p, Tt) {
    .Call(`_dbn_batch_update_Z_ordinal_fast`, R_4d, Z_4d, Theta_4d, M, IR, IR_time_indices, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
precompute_time_indices <- function(IR, n_row, n_col, p, Tt) {
    .Call(`_dbn_precompute_time_indices`, IR, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
update_mu_dynamic <- function(Z_4d, Theta_4d, M_prev, g2, a_g, b_g, n_row, n_col, p, Tt) {
    .Call(`_dbn_update_mu_dynamic`, Z_4d, Theta_4d, M_prev, g2, a_g, b_g, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
batch_ffbs_all_relations <- function(Z_4d, M, Aarray, Barray, sigma2, n_row, n_col, p, Tt) {
    .Call(`_dbn_batch_ffbs_all_relations`, Z_4d, M, Aarray, Barray, sigma2, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
update_AB_batch_extended <- function(Theta_4d, Aarray_old, Barray_old, sigma2, tauA2, tauB2, ar1, rhoA, rhoB, n_row, n_col, p, Tt, prior_kind = "rw", kappaA_inv = 0.0, kappaB_inv = 0.0) {
    .Call(`_dbn_update_AB_batch_extended`, Theta_4d, Aarray_old, Barray_old, sigma2, tauA2, tauB2, ar1, rhoA, rhoB, n_row, n_col, p, Tt, prior_kind, kappaA_inv, kappaB_inv)
}

#' @keywords internal
#' @noRd
update_variances_dynamic <- function(Theta_4d, Z_4d, M, Aarray, Barray, a_sig, b_sig, n_row, n_col, p, Tt, is_gaussian = FALSE, exclude_diagonal = FALSE) {
    .Call(`_dbn_update_variances_dynamic`, Theta_4d, Z_4d, M, Aarray, Barray, a_sig, b_sig, n_row, n_col, p, Tt, is_gaussian, exclude_diagonal)
}

#' @keywords internal
#' @noRd
batch_ffbs_all_relations_blocked <- function(Z_4d, M, Aarray, Barray, sigma2, n_row, n_col, p, Tt) {
    .Call(`_dbn_batch_ffbs_all_relations_blocked`, Z_4d, M, Aarray, Barray, sigma2, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
update_AB_batch_large <- function(Theta_4d, Aarray_old, Barray_old, sigma2, tauA2, tauB2, ar1, rhoA, rhoB, n_row, n_col, p, Tt, prior_kind = "rw", kappaA_inv = 0.0, kappaB_inv = 0.0) {
    .Call(`_dbn_update_AB_batch_large`, Theta_4d, Aarray_old, Barray_old, sigma2, tauA2, tauB2, ar1, rhoA, rhoB, n_row, n_col, p, Tt, prior_kind, kappaA_inv, kappaB_inv)
}

#' @keywords internal
#' @noRd
compute_process_variance_blocked <- function(Theta_4d, Aarray, Barray, n_row, n_col, p, Tt) {
    .Call(`_dbn_compute_process_variance_blocked`, Theta_4d, Aarray, Barray, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
compute_gaussian_obs_residuals_dynamic_cpp <- function(Z_4d, Theta_4d, M, n_row, n_col, p, Tt) {
    .Call(`_dbn_compute_gaussian_obs_residuals_dynamic_cpp`, Z_4d, Theta_4d, M, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
compute_ar1_innovation_ss_cpp <- function(ABarray, rho, n, Tt) {
    .Call(`_dbn_compute_ar1_innovation_ss_cpp`, ABarray, rho, n, Tt)
}

#' @keywords internal
#' @noRd
compute_rho_update_cpp <- function(ABarray, n, Tt) {
    .Call(`_dbn_compute_rho_update_cpp`, ABarray, n, Tt)
}

#' Fast FFBS for Bilinear Model
#'
#' @description Efficient FFBS that avoids Kronecker products.
#'   Supports rectangular (bipartite) Theta via scalar variance approximation.
#' @param Z Observations (n_row x n_col x T)
#' @param mu Baseline mean (n_row x n_col)
#' @param A_array Time-varying A matrices (n_row x n_row x T)
#' @param B_array Time-varying B matrices (n_col x n_col x T)
#' @param sigma2_proc Process variance
#' @param sigma2_obs Observation variance (default 1.0)
#' @return Sampled Theta array (n_row x n_col x T)
#' @keywords internal
#' @noRd
ffbs_bilinear <- function(Z, mu, A_array, B_array, sigma2_proc, sigma2_obs = 1.0) {
    .Call(`_dbn_ffbs_bilinear`, Z, mu, A_array, B_array, sigma2_proc, sigma2_obs)
}

#' Fast FFBS for Dynamic Linear Model in C++
#' 
#' @description C++ implementation of ffbs_dlm with OpenMP parallelization
#' @param y List of observation vectors (length T)
#' @param Flist List of design matrices (T x (r x p))
#' @param V Observation variance matrix (p x p)
#' @param W State innovation variance matrix (r x r)
#' @param m0 Prior mean vector (r x 1)
#' @param C0 Prior covariance matrix (r x r)
#' @param ar1 Logical: use AR(1) dynamics instead of random walk
#' @param rho AR(1) coefficient (used if ar1=TRUE)
#' @return Matrix of sampled state vectors (r x T)
#' @keywords internal
#' @noRd
ffbs_dlm_cpp <- function(y, Flist, V, W, m0, C0, ar1 = FALSE, rho = 0.0) {
    .Call(`_dbn_ffbs_dlm_cpp`, y, Flist, V, W, m0, C0, ar1, rho)
}

#' Batch FFBS for multiple independent DLM problems
#' 
#' @description Parallelized FFBS for updating all rows of A or columns of B simultaneously
#' @param Y_batch Stacked observations (batch_size x T)
#' @param F_batch Design matrices for each problem (batch_size x T x state_dim x obs_dim)
#' @param V_batch Observation variances (can be scalar or vector of length batch_size)
#' @param W State innovation variance (common across batch)
#' @param m0 Prior mean (common)
#' @param C0 Prior covariance (common)
#' @param ar1 Use AR(1) dynamics
#' @param rho AR(1) coefficient
#' @return Matrix of sampled states (batch_size x state_dim x T)
#' @keywords internal
#' @noRd
ffbs_dlm_batch_cpp <- function(Y_batch, F_batch, V_batch, W, m0, C0, ar1 = FALSE, rho = 0.0) {
    .Call(`_dbn_ffbs_dlm_batch_cpp`, Y_batch, F_batch, V_batch, W, m0, C0, ar1, rho)
}

#' Structured FFBS for Theta
#'
#' @description Memory-efficient FFBS that avoids creating n^2 x n^2 matrices.
#'   Supports rectangular (bipartite) Theta via row-covariance approximation.
#' @param Z Observations (n_row x n_col x T array as cube)
#' @param mu Baseline mean (n_row x n_col matrix)
#' @param A_array Time-varying A matrices (n_row x n_row x T)
#' @param B_array Time-varying B matrices (n_col x n_col x T)
#' @param sigma2 Innovation variance (scalar)
#' @return Sampled Theta array (n_row x n_col x T)
ffbs_theta_struct_5arg_cpp <- function(Z, mu, A_array, B_array, sigma2) {
    .Call(`_dbn_ffbs_theta_struct_5arg_cpp`, Z, mu, A_array, B_array, sigma2)
}

#' @keywords internal
#' @noRd
ffbs_theta_struct_cpp <- function(Z, mu, A_array, B_array, sigma2_proc, sigma2_obs) {
    .Call(`_dbn_ffbs_theta_struct_cpp`, Z, mu, A_array, B_array, sigma2_proc, sigma2_obs)
}

compute_gaussian_obs_residuals_cpp <- function(Z, Theta, M) {
    .Call(`_dbn_compute_gaussian_obs_residuals_cpp`, Z, Theta, M)
}

compute_gaussian_obs_residuals_4d_cpp <- function(Z_flat, Theta_flat, M_flat, m, p, Tt) {
    .Call(`_dbn_compute_gaussian_obs_residuals_4d_cpp`, Z_flat, Theta_flat, M_flat, m, p, Tt)
}

compute_gaussian_obs_residuals_batch_cpp <- function(Z, Theta, M, m, p, Tt) {
    .Call(`_dbn_compute_gaussian_obs_residuals_batch_cpp`, Z, Theta, M, m, p, Tt)
}

#' @keywords internal
#' @noRd
forward_hmm <- function(Theta_avg, A_list, B_list, Pi, sigma2, pi0) {
    .Call(`_dbn_forward_hmm`, Theta_avg, A_list, B_list, Pi, sigma2, pi0)
}

#' @keywords internal
#' @noRd
forward_hmm_fast <- function(Theta_avg, A_list, B_list, Pi, sigma2, pi0, beam_width = 0L) {
    .Call(`_dbn_forward_hmm_fast`, Theta_avg, A_list, B_list, Pi, sigma2, pi0, beam_width)
}

#' @keywords internal
#' @noRd
backward_sample <- function(log_alpha, Pi) {
    .Call(`_dbn_backward_sample`, log_alpha, Pi)
}

#' @keywords internal
#' @noRd
backward_sample_fast <- function(log_alpha, Pi) {
    .Call(`_dbn_backward_sample_fast`, log_alpha, Pi)
}

#' @keywords internal
#' @noRd
build_regime_arrays <- function(S, A_list, B_list, m, Tt) {
    .Call(`_dbn_build_regime_arrays`, S, A_list, B_list, m, Tt)
}

#' @keywords internal
#' @noRd
collect_regime_thetas <- function(Theta_avg, S, regime, m) {
    .Call(`_dbn_collect_regime_thetas`, Theta_avg, S, regime, m)
}

#' @keywords internal
#' @noRd
count_transitions <- function(S, R) {
    .Call(`_dbn_count_transitions`, S, R)
}

#' @keywords internal
#' @noRd
compute_regime_residuals <- function(A_list, I_m, R, m) {
    .Call(`_dbn_compute_regime_residuals`, A_list, I_m, R, m)
}

#' @keywords internal
#' @noRd
init_states_spectral <- function(Y, R, m, p, Tt) {
    .Call(`_dbn_init_states_spectral`, Y, R, m, p, Tt)
}

#' Sample from inverse Wishart distribution with stability checks
#' 
#' @param nu Degrees of freedom
#' @param S Scale matrix
#' @return Sample from inverse Wishart distribution
#' @keywords internal
#' @noRd
rinvwishart_stable <- function(nu, S) {
    .Call(`_dbn_rinvwishart_stable`, nu, S)
}

#' Check if proposed innovation covariance is valid
#' 
#' @param Sigma_e Proposed innovation covariance
#' @param min_eigenvalue Minimum allowed eigenvalue
#' @param max_condition Maximum allowed condition number
#' @return Validity indicator
#' @keywords internal
#' @noRd
is_valid_innovation_cov <- function(Sigma_e, min_eigenvalue = 1e-6, max_condition = 1e6) {
    .Call(`_dbn_is_valid_innovation_cov`, Sigma_e, min_eigenvalue, max_condition)
}

#' Adaptive Metropolis-Hastings update for innovation covariance
#' 
#' @param Sigma_e_current Current innovation covariance
#' @param nu Prior degrees of freedom
#' @param S Prior scale matrix
#' @param X Latent states (p x q x T)
#' @param A Actor transition matrix
#' @param B Latent transition matrix
#' @param adapt_scale Adaptation scale parameter
#' @return List with new covariance and acceptance indicator
#' @keywords internal
#' @noRd
update_innovation_cov_adaptive <- function(Sigma_e_current, nu, S, X, A, B, adapt_scale = 0.1) {
    .Call(`_dbn_update_innovation_cov_adaptive`, Sigma_e_current, nu, S, X, A, B, adapt_scale)
}

#' Compute impulse response for constant A,B matrices
#'
#' Low-level C++ helper used by `compute_irf()`. Not user-facing; the public
#' entry point is `compute_irf()`.
#'
#' @param A Transition matrix A (m x m)
#' @param B Transition matrix B (m x m)
#' @param S Shock matrix (m x m)
#' @param H Number of horizons to compute
#' @return Cube of impulse responses (m x m x H+1)
#' @keywords internal
#' @noRd
impulse_response_const <- function(A, B, S, H) {
    .Call(`_dbn_impulse_response_const`, A, B, S, H)
}

#' Compute impulse response for time-varying A,B matrices
#'
#' Low-level C++ helper used by `compute_irf()`. Not user-facing; the public
#' entry point is `compute_irf()`.
#'
#' @param Aarray Cube of A matrices over time (m x m x T)
#' @param Barray Cube of B matrices over time (m x m x T)
#' @param S Shock matrix (m x m)
#' @param t0 Time index of shock (0-based)
#' @param H Number of horizons to compute
#' @return Cube of impulse responses (m x m x H+1)
#' @keywords internal
#' @noRd
impulse_response_dynamic <- function(Aarray, Barray, S, t0, H) {
    .Call(`_dbn_impulse_response_dynamic`, Aarray, Barray, S, t0, H)
}

#' @keywords internal
#' @noRd
compute_A_lowrank <- function(U, alpha_t) {
    .Call(`_dbn_compute_A_lowrank`, U, alpha_t)
}

#' @keywords internal
#' @noRd
compute_all_A_lowrank <- function(U, alpha, Tt) {
    .Call(`_dbn_compute_all_A_lowrank`, U, alpha, Tt)
}

#' @keywords internal
#' @noRd
build_F_alpha_vectorized <- function(U, Theta_prev, B_t, p, Tt) {
    .Call(`_dbn_build_F_alpha_vectorized`, U, Theta_prev, B_t, p, Tt)
}

#' @keywords internal
#' @noRd
build_y_alpha_vectorized <- function(Theta_flat, M, m, p, Tt) {
    .Call(`_dbn_build_y_alpha_vectorized`, Theta_flat, M, m, p, Tt)
}

#' @keywords internal
#' @noRd
loglik_U <- function(U, alpha, Theta_avg, Barray, sigma2) {
    .Call(`_dbn_loglik_U`, U, alpha, Theta_avg, Barray, sigma2)
}

#' @keywords internal
#' @noRd
cayley_transform <- function(U, W, epsilon) {
    .Call(`_dbn_cayley_transform`, U, W, epsilon)
}

#' @keywords internal
#' @noRd
generate_skew_proposal <- function(m, norm_cap) {
    .Call(`_dbn_generate_skew_proposal`, m, norm_cap)
}

#' @keywords internal
#' @noRd
update_B_lowrank_batch <- function(Theta_flat, U, alpha, sigma2_proc, tau_B2, ar1, rho, m, p, Tt) {
    .Call(`_dbn_update_B_lowrank_batch`, Theta_flat, U, alpha, sigma2_proc, tau_B2, ar1, rho, m, p, Tt)
}

#' @keywords internal
#' @noRd
compute_lowrank_residuals <- function(Theta_flat, M, U, alpha, Barray, m, p, Tt) {
    .Call(`_dbn_compute_lowrank_residuals`, Theta_flat, M, U, alpha, Barray, m, p, Tt)
}

#' @keywords internal
#' @noRd
compute_sigma2_lowrank_batch <- function(Theta, Aarray, Barray, m, p, Tt) {
    .Call(`_dbn_compute_sigma2_lowrank_batch`, Theta, Aarray, Barray, m, p, Tt)
}

#' @keywords internal
#' @noRd
compute_sigma2_simd <- function(Theta, U, alpha, Barray, m, p, Tt, r) {
    .Call(`_dbn_compute_sigma2_simd`, Theta, U, alpha, Barray, m, p, Tt, r)
}

#' @keywords internal
#' @noRd
ffbs_theta_all_relations <- function(Z_all, M_all, Aarray, Barray, sigma2_proc, sigma2_obs, m, p, Tt) {
    .Call(`_dbn_ffbs_theta_all_relations`, Z_all, M_all, Aarray, Barray, sigma2_proc, sigma2_obs, m, p, Tt)
}

#' @keywords internal
#' @noRd
ffbs_theta_blocked <- function(Z_all, M_all, Aarray, Barray, sigma2_proc, sigma2_obs, m, p, Tt) {
    .Call(`_dbn_ffbs_theta_blocked`, Z_all, M_all, Aarray, Barray, sigma2_proc, sigma2_obs, m, p, Tt)
}

#' @keywords internal
#' @noRd
update_alpha_optimized <- function(Theta, U, Barray, sigma2_proc, tau_alpha2, ar1_alpha, rho_alpha, m, p, Tt, r) {
    .Call(`_dbn_update_alpha_optimized`, Theta, U, Barray, sigma2_proc, tau_alpha2, ar1_alpha, rho_alpha, m, p, Tt, r)
}

#' @keywords internal
#' @noRd
update_B_blocked <- function(Theta, Aarray, sigma2_proc, tau_B2, ar1_B, rho_B, m, p, Tt) {
    .Call(`_dbn_update_B_blocked`, Theta, Aarray, sigma2_proc, tau_B2, ar1_B, rho_B, m, p, Tt)
}

#' @keywords internal
#' @noRd
update_Z_ordinal_global <- function(Z_all, Theta_all, M_all, IR_list, m, p, Tt) {
    invisible(.Call(`_dbn_update_Z_ordinal_global`, Z_all, Theta_all, M_all, IR_list, m, p, Tt))
}

#' @keywords internal
#' @noRd
update_B_parallel <- function(Theta, Aarray, sigma2_proc, tau_B2, ar1_B, rho_B, m, p, Tt) {
    .Call(`_dbn_update_B_parallel`, Theta, Aarray, sigma2_proc, tau_B2, ar1_B, rho_B, m, p, Tt)
}

#' @keywords internal
#' @noRd
update_alpha_batch <- function(Theta, U, Barray, sigma2_proc, tau_alpha2, ar1_alpha, rho_alpha, m, p, Tt, r) {
    .Call(`_dbn_update_alpha_batch`, Theta, U, Barray, sigma2_proc, tau_alpha2, ar1_alpha, rho_alpha, m, p, Tt, r)
}

#' @keywords internal
#' @noRd
update_Z_ordinal_vectorized <- function(Z_all, Theta_all, M_all, IR_list, m, p, Tt) {
    invisible(.Call(`_dbn_update_Z_ordinal_vectorized`, Z_all, Theta_all, M_all, IR_list, m, p, Tt))
}

#' Fast parallel Gaussian approximation for ordinal data
#' @keywords internal
#' @noRd
rz_gaussian_approx_cpp <- function(R, Z, EZ, sigma = 1.0) {
    .Call(`_dbn_rz_gaussian_approx_cpp`, R, Z, EZ, sigma)
}

#' @keywords internal
#' @noRd
piecewise_theta_update_cpp <- function(Z_block, Theta_prev, M, A, B, s2, is_first_block) {
    .Call(`_dbn_piecewise_theta_update_cpp`, Z_block, Theta_prev, M, A, B, s2, is_first_block)
}

#' @keywords internal
#' @noRd
piecewise_suff_stats_A_cpp <- function(Theta_block, Theta_prev, M, B, is_first_block) {
    .Call(`_dbn_piecewise_suff_stats_A_cpp`, Theta_block, Theta_prev, M, B, is_first_block)
}

#' @keywords internal
#' @noRd
piecewise_suff_stats_B_cpp <- function(Theta_block, Theta_prev, M, A, is_first_block) {
    .Call(`_dbn_piecewise_suff_stats_B_cpp`, Theta_block, Theta_prev, M, A, is_first_block)
}

#' @keywords internal
#' @noRd
piecewise_block_update_cpp <- function(Z_4d, Theta_4d, M, A_blocks, B_blocks, block_starts, block_ends, s2, t2, symmetric) {
    .Call(`_dbn_piecewise_block_update_cpp`, Z_4d, Theta_4d, M, A_blocks, B_blocks, block_starts, block_ends, s2, t2, symmetric)
}

#' @keywords internal
#' @noRd
piecewise_mcmc_iter_cpp <- function(Z, Theta, M, A_blocks, B_blocks, block_starts, block_ends, s2, t2, g2, symmetric) {
    .Call(`_dbn_piecewise_mcmc_iter_cpp`, Z, Theta, M, A_blocks, B_blocks, block_starts, block_ends, s2, t2, g2, symmetric)
}

#' Validate transition matrix proposals
#' 
#' @param A_prop Proposed actor transition matrix
#' @param B_prop Proposed latent transition matrix
#' @param p Number of actors
#' @param q Latent dimension
#' @param check_stationary Check stationarity condition
#' @return Validity indicator
#' @keywords internal
#' @noRd
validate_transition_proposal <- function(A_prop, B_prop, p, q, check_stationary = TRUE) {
    .Call(`_dbn_validate_transition_proposal`, A_prop, B_prop, p, q, check_stationary)
}

#' Adaptive random walk proposal for transition matrices
#' 
#' @param A_current Current actor transition matrix
#' @param B_current Current latent transition matrix
#' @param step_size_A Step size for A
#' @param step_size_B Step size for B
#' @param max_attempts Maximum proposal attempts
#' @return List with proposed matrices and validity indicator
#' @keywords internal
#' @noRd
propose_transition_adaptive <- function(A_current, B_current, step_size_A = 0.1, step_size_B = 0.1, max_attempts = 10L) {
    .Call(`_dbn_propose_transition_adaptive`, A_current, B_current, step_size_A, step_size_B, max_attempts)
}

#' Check for edge cases in the data
#' 
#' @param Y Data cube (p x p x T)
#' @return List with edge case indicators
#' @keywords internal
#' @noRd
check_edge_cases <- function(Y) {
    .Call(`_dbn_check_edge_cases`, Y)
}

#' Fast rank-likelihood sampler in C++
#' 
#' @description Port of rz_fc() to C++ for ~8-15x speedup on large ordinal networks
#' @param R Observed ranks (vectorized matrix)
#' @param Z Current latent values (vectorized)
#' @param EZ Expected values (vectorized)
#' @param iranks List of indices for each rank level
#' @return Updated Z vector
#' @keywords internal
#' @noRd
rz_fc_cpp <- function(R, Z, EZ, iranks) {
    .Call(`_dbn_rz_fc_cpp`, R, Z, EZ, iranks)
}

#' Build rank indices from rank matrix
#' 
#' @description Helper to convert rank matrix to iranks format for C++
#' @param R Rank matrix
#' @return List of indices for each rank
#' @keywords internal
#' @noRd
build_rank_indices <- function(R) {
    .Call(`_dbn_build_rank_indices`, R)
}

#' @keywords internal
#' @noRd
rz_fc_matrix <- function(R, Z_current, EZ, iranks) {
    .Call(`_dbn_rz_fc_matrix`, R, Z_current, EZ, iranks)
}

#' @keywords internal
#' @noRd
rz_fc_batch <- function(R, Z_current, EZ, IR_list, n_row, n_col, p, Tt) {
    .Call(`_dbn_rz_fc_batch`, R, Z_current, EZ, IR_list, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
precompute_rank_structure <- function(R, n_row, n_col, p, Tt) {
    .Call(`_dbn_precompute_rank_structure`, R, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
bilinear_product_fast <- function(A, Theta, B) {
    .Call(`_dbn_bilinear_product_fast`, A, Theta, B)
}

#' @keywords internal
#' @noRd
compute_bilinear_residuals <- function(Theta_flat, Aarray, Barray, m, p, Tt) {
    .Call(`_dbn_compute_bilinear_residuals`, Theta_flat, Aarray, Barray, m, p, Tt)
}

#' @keywords internal
#' @noRd
compute_bilinear_residuals_fast <- function(Theta, Aarray, Barray, m, p, Tt) {
    .Call(`_dbn_compute_bilinear_residuals_fast`, Theta, Aarray, Barray, m, p, Tt)
}

#' @keywords internal
#' @noRd
compute_observation_residuals <- function(Z_flat, Theta_flat, M, m, p, Tt) {
    .Call(`_dbn_compute_observation_residuals`, Z_flat, Theta_flat, M, m, p, Tt)
}

#' @keywords internal
#' @noRd
compute_zscores_batch <- function(Y, means, sds, n_row, n_col, p, Tt) {
    .Call(`_dbn_compute_zscores_batch`, Y, means, sds, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
update_Z_batch <- function(R_flat, Theta_flat, M, IR_list_flat, n_row, n_col, p, Tt) {
    .Call(`_dbn_update_Z_batch`, R_flat, Theta_flat, M, IR_list_flat, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
build_regime_arrays_vectorized <- function(S, A_list, B_list, n_row, n_col, Tt) {
    .Call(`_dbn_build_regime_arrays_vectorized`, S, A_list, B_list, n_row, n_col, Tt)
}

#' @keywords internal
#' @noRd
compute_outer_products_batch <- function(U) {
    .Call(`_dbn_compute_outer_products_batch`, U)
}

#' @keywords internal
#' @noRd
compute_A_lowrank_batch <- function(outer_prods, alpha, Tt) {
    .Call(`_dbn_compute_A_lowrank_batch`, outer_prods, alpha, Tt)
}

#' @keywords internal
#' @noRd
update_A_suffstat_cpp <- function(Theta_arr, Aarray_old, sigma2, tau2, tau2_init_per_row, rho_max = 0.0, max_rejects = 50L) {
    .Call(`_dbn_update_A_suffstat_cpp`, Theta_arr, Aarray_old, sigma2, tau2, tau2_init_per_row, rho_max, max_rejects)
}

update_A_symmetric_mh_cpp <- function(Z_arr, Aarray_init, sigma2, tau_A2, kappa_A2, proposal_sd, n_sweeps, burn = 0L, odens = 1L, adapt = TRUE) {
    .Call(`_dbn_update_A_symmetric_mh_cpp`, Z_arr, Aarray_init, sigma2, tau_A2, kappa_A2, proposal_sd, n_sweeps, burn, odens, adapt)
}

update_A_ar1_mh_diag_cpp <- function(Z_arr, Aarray_init, Abar, phi, sigma2, sigma2_diag, tau_Delta2, proposal_sd, n_sweeps, burn = 0L, odens = 1L, adapt = TRUE) {
    .Call(`_dbn_update_A_ar1_mh_diag_cpp`, Z_arr, Aarray_init, Abar, phi, sigma2, sigma2_diag, tau_Delta2, proposal_sd, n_sweeps, burn, odens, adapt)
}

update_A_ar1_mh_cpp <- function(Z_arr, Aarray_init, Abar, phi, sigma2, tau_Delta2, proposal_sd, n_sweeps, burn = 0L, odens = 1L, adapt = TRUE) {
    .Call(`_dbn_update_A_ar1_mh_cpp`, Z_arr, Aarray_init, Abar, phi, sigma2, tau_Delta2, proposal_sd, n_sweeps, burn, odens, adapt)
}

#' Reshape 4D array to 3D for C++ processing
#' @description Efficiently reshape Z from n_row x n_col x p x Tt to n_row x n_col x (p*Tt)
#' @param Z_4d Input 4D array as R array
#' @param n_row Number of row nodes (senders)
#' @param n_col Number of column nodes (receivers)
#' @param p Number of relations
#' @param Tt Number of time points
#' @return 3D cube for C++ processing
#' @keywords internal
#' @noRd
reshape_Z_to_cube <- function(Z_4d, n_row, n_col, p, Tt) {
    .Call(`_dbn_reshape_Z_to_cube`, Z_4d, n_row, n_col, p, Tt)
}

#' Compute SSE for diagonal elements efficiently
#' @description Compute sum of squared errors for diagonal elements of B matrices
#' @param B_list List of B matrices
#' @param K Number of matrices
#' @return SSE value
#' @keywords internal
#' @noRd
compute_diagonal_sse <- function(B_list, K) {
    .Call(`_dbn_compute_diagonal_sse`, B_list, K)
}

#' Compute sum of squared deviations from identity for A or B arrays
#' @description Efficiently compute sum of squared deviations from the identity matrix
#'   for each matrix slice of A or B from time t = 2 to Tt
#' @param ABarray 3D array of A or B matrices (m x m x Tt)
#' @param m Number of nodes (dimension of the square matrix)
#' @param Tt Number of time points
#' @return Sum of squared deviations
#' @keywords internal
#' @noRd
compute_deviation_sum <- function(ABarray, m, Tt) {
    .Call(`_dbn_compute_deviation_sum`, ABarray, m, Tt)
}

#' Compute mean M for static model
#' @description Efficiently compute mean of Z across time for each relation
#' @param Z_flat Flattened Z array (n_row*n_col x p*Tt)
#' @param n_row Number of row nodes
#' @param n_col Number of column nodes
#' @param p Number of relations
#' @param Tt Number of time points
#' @return M array (n_row x n_col x p)
#' @keywords internal
#' @noRd
compute_M_static <- function(Z_flat, n_row, n_col, p, Tt) {
    .Call(`_dbn_compute_M_static`, Z_flat, n_row, n_col, p, Tt)
}

#' Compute residual sum of squares for static model
#' @description Compute sum((Z - M)^2) across all times and relations
#' @param Z_4d Original Z array (n_row x n_col x p x Tt) as flattened vector
#' @param M Mean array (n_row x n_col x p)
#' @param n_row Number of row nodes
#' @param n_col Number of column nodes
#' @param p Number of relations
#' @param Tt Number of time points
#' @return Sum of squared residuals
#' @keywords internal
#' @noRd
compute_rss_static <- function(Z_4d, M, n_row, n_col, p, Tt) {
    .Call(`_dbn_compute_rss_static`, Z_4d, M, n_row, n_col, p, Tt)
}

#' Reshape for large networks with parallelization
#' @description Parallel version of reshape_Z_to_cube for large networks
#' @param Z_4d Input 4D array as R array
#' @param n_row Number of row nodes
#' @param n_col Number of column nodes
#' @param p Number of relations
#' @param Tt Number of time points
#' @return 3D cube for C++ processing
#' @keywords internal
#' @noRd
reshape_Z_to_cube_parallel <- function(Z_4d, n_row, n_col, p, Tt) {
    .Call(`_dbn_reshape_Z_to_cube_parallel`, Z_4d, n_row, n_col, p, Tt)
}

#' M computation with blocked summation for numerical stability
#' @description Compute mean with blocked summation for large networks
#' @param Z_flat Flattened Z array (n_row*n_col x p*Tt)
#' @param n_row Number of row nodes
#' @param n_col Number of column nodes
#' @param p Number of relations
#' @param Tt Number of time points
#' @return M array (n_row x n_col x p)
#' @keywords internal
#' @noRd
compute_M_static_blocked <- function(Z_flat, n_row, n_col, p, Tt) {
    .Call(`_dbn_compute_M_static_blocked`, Z_flat, n_row, n_col, p, Tt)
}

#' RSS computation with parallel reduction
#' @description Parallel computation of residual sum of squares
#' @param Z_cube Z array as cube (n_row x n_col x p*Tt)
#' @param M Mean array (n_row x n_col x p)
#' @param n_row Number of row nodes
#' @param n_col Number of column nodes
#' @param p Number of relations
#' @param Tt Number of time points
#' @return Sum of squared residuals
#' @keywords internal
#' @noRd
compute_rss_static_parallel <- function(Z_cube, M, n_row, n_col, p, Tt) {
    .Call(`_dbn_compute_rss_static_parallel`, Z_cube, M, n_row, n_col, p, Tt)
}

#' Cache-efficient B update for static model (sender effects)
#' @description B1 (sender effects, n_row x n_row) update using tiled matrix operations.
#'   Model: Z_jt = B * M_j + E, so regression is column-wise:
#'   z_c = B * m_c, giving XtX = sum M_j * M_j' and XtY = sum Z_jt * M_j'
#' @param Z_cube Z array as cube (n_row x n_col x p*Tt)
#' @param M Mean array (n_row x n_col x p)
#' @param s2 Observation variance
#' @param t2 Prior variance
#' @param n_row Number of row nodes (senders)
#' @param n_col Number of column nodes (receivers)
#' @param p Number of relations
#' @param Tt Number of time points
#' @return Updated B matrix (n_row x n_row)
#' @keywords internal
#' @noRd
update_B_static_tiled <- function(Z_cube, M, s2, t2, n_row, n_col, p, Tt) {
    .Call(`_dbn_update_B_static_tiled`, Z_cube, M, s2, t2, n_row, n_col, p, Tt)
}

cg_benchmark_tridiag_cpp <- function(Y_arr_3d, M_mat, A_arr, sigma2, sigma2_obs, pairs) {
    .Call(`_dbn_cg_benchmark_tridiag_cpp`, Y_arr_3d, M_mat, A_arr, sigma2, sigma2_obs, pairs)
}

cg_benchmark_blockdiag_cpp <- function(Y_arr_3d, M_mat, A_arr, sigma2, sigma2_obs, pairs) {
    .Call(`_dbn_cg_benchmark_blockdiag_cpp`, Y_arr_3d, M_mat, A_arr, sigma2, sigma2_obs, pairs)
}

#' @keywords internal
#' @noRd
theta_pcg_sampler_cpp <- function(Y_arr_3d, M_mat, A_arr, sigma2, sigma2_obs, pairs) {
    .Call(`_dbn_theta_pcg_sampler_cpp`, Y_arr_3d, M_mat, A_arr, sigma2, sigma2_obs, pairs)
}

theta_pcg_asym_sampler_cpp <- function(Y_arr_3d, M_mat, A_arr, B_arr, sigma2, sigma2_obs) {
    .Call(`_dbn_theta_pcg_asym_sampler_cpp`, Y_arr_3d, M_mat, A_arr, B_arr, sigma2, sigma2_obs)
}

#' @keywords internal
#' @noRd
update_A_batch <- function(Theta_all_1, Theta_all_2, Theta_all_3, Theta_all_4, Aarray, Barray, sigma2, tauA2, ar1 = FALSE, rhoA = 0.0, p = 1L) {
    .Call(`_dbn_update_A_batch`, Theta_all_1, Theta_all_2, Theta_all_3, Theta_all_4, Aarray, Barray, sigma2, tauA2, ar1, rhoA, p)
}

#' @keywords internal
#' @noRd
update_B_batch <- function(Theta_all_1, Theta_all_2, Theta_all_3, Theta_all_4, Aarray, Barray, sigma2, tauB2, ar1 = FALSE, rhoB = 0.0, p = 1L) {
    .Call(`_dbn_update_B_batch`, Theta_all_1, Theta_all_2, Theta_all_3, Theta_all_4, Aarray, Barray, sigma2, tauB2, ar1, rhoB, p)
}

#' Update A and B matrices for static model (C++ version)
#'
#' @description Fast C++ implementation of update_AB_static.
#'   Supports bipartite networks where Theta is n_row x n_col (rectangular).
#'   A is n_row x n_row (sender dynamics), B is n_col x n_col (receiver dynamics).
#' @param Theta_prev Previous Theta values (n_row x n_col x n_times)
#' @param Theta_curr Current Theta values (n_row x n_col x n_times)
#' @param B_init Initial B matrix (n_col x n_col)
#' @param tau_A2 Prior variance for A
#' @param tau_B2 Prior variance for B
#' @param sigma2 Innovation variance
#' @return List with updated A and B matrices
#' @keywords internal
#' @noRd
update_AB_static_cpp <- function(Theta_prev, Theta_curr, B_init, tau_A2, tau_B2, sigma2) {
    .Call(`_dbn_update_AB_static_cpp`, Theta_prev, Theta_curr, B_init, tau_A2, tau_B2, sigma2)
}

#' Build design matrix F for alpha updates (C++ version)
#' 
#' @description Fast C++ implementation of build_F_alpha
#' @param U Orthonormal matrix (m x r)
#' @param Theta_prev Previous Theta values (m x m x T)
#' @param B_array B matrices over time (m x m x T)
#' @param compute_all Compute for all time points at once
#' @return Design matrix F (m^2*T x r) if compute_all=true, else (m^2 x r)
#' @keywords internal
#' @noRd
build_F_alpha_cpp <- function(U, Theta_prev, B_array, compute_all = FALSE) {
    .Call(`_dbn_build_F_alpha_cpp`, U, Theta_prev, B_array, compute_all)
}

#' @keywords internal
#' @noRd
compute_XB_tensor <- function(X, B, m, p, n) {
    .Call(`_dbn_compute_XB_tensor`, X, B, m, p, n)
}

#' @keywords internal
#' @noRd
update_B_static <- function(Z, M, s2, t2, n_row, n_col, p, n) {
    .Call(`_dbn_update_B_static`, Z, M, s2, t2, n_row, n_col, p, n)
}

#' @keywords internal
#' @noRd
broadcast_M_and_compute_EZ <- function(M, s2, n_row, n_col, p, Tt) {
    .Call(`_dbn_broadcast_M_and_compute_EZ`, M, s2, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
compute_s2_update <- function(Z_field, M, m, p, Tt, a_prior, b_prior) {
    .Call(`_dbn_compute_s2_update`, Z_field, M, m, p, Tt, a_prior, b_prior)
}

#' @keywords internal
#' @noRd
update_variances_batch <- function(sum_squares, counts, a_priors, b_priors) {
    .Call(`_dbn_update_variances_batch`, sum_squares, counts, a_priors, b_priors)
}

#' @keywords internal
#' @noRd
stabilize_matrix <- function(M, min_eig = 1e-6) {
    .Call(`_dbn_stabilize_matrix`, M, min_eig)
}

#' @keywords internal
#' @noRd
update_Z_dynamic <- function(R, Z_current, Theta, M, IR, n_row, n_col, p, Tt) {
    .Call(`_dbn_update_Z_dynamic`, R, Z_current, Theta, M, IR, n_row, n_col, p, Tt)
}

#' @keywords internal
#' @noRd
precompute_products <- function(Aarray, Barray, m, Tt) {
    .Call(`_dbn_precompute_products`, Aarray, Barray, m, Tt)
}

#' @keywords internal
#' @noRd
compute_residual_sum_squares <- function(Z_field, M, p) {
    .Call(`_dbn_compute_residual_sum_squares`, Z_field, M, p)
}

#' @keywords internal
#' @noRd
compute_innovation_variance <- function(X_curr, X_prev, ar1 = FALSE, rho = 0.0) {
    .Call(`_dbn_compute_innovation_variance`, X_curr, X_prev, ar1, rho)
}

#' @keywords internal
#' @noRd
compute_M_update <- function(Z_field, g2, m, p) {
    .Call(`_dbn_compute_M_update`, Z_field, g2, m, p)
}

#' @keywords internal
#' @noRd
compute_AB_innovations <- function(Aarray, Barray, ar1 = FALSE, rhoA = 0.0, rhoB = 0.0) {
    .Call(`_dbn_compute_AB_innovations`, Aarray, Barray, ar1, rhoA, rhoB)
}

